# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vaaniUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_vaaniUi(object):
    def setupUi(self, vaaniUi):
        vaaniUi.setObjectName("vaaniUi")
        vaaniUi.resize(799, 597)
        self.centralwidget = QtWidgets.QWidget(vaaniUi)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -10, 811, 611))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../anime1.gif"))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(530, 510, 93, 51))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(650, 510, 91, 51))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 271, 71))
        self.textBrowser.setStyleSheet("background: \"white\";\n"
"font:75 \"System\";")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(510, 10, 271, 71))
        self.textBrowser_2.setStyleSheet("font: 75 8pt \"System\";\n" "background: \"white\";")
        self.textBrowser_2.setObjectName("textBrowser_2")
        vaaniUi.setCentralWidget(self.centralwidget)

        self.retranslateUi(vaaniUi)
        QtCore.QMetaObject.connectSlotsByName(vaaniUi)

    def retranslateUi(self, vaaniUi):
        _translate = QtCore.QCoreApplication.translate
        vaaniUi.setWindowTitle(_translate("vaaniUi", "MainWindow"))
        self.pushButton.setText(_translate("vaaniUi", "RUN"))
        self.pushButton_2.setText(_translate("vaaniUi", "END"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    vaaniUi = QtWidgets.QMainWindow()
    ui = Ui_vaaniUi()
    ui.setupUi(vaaniUi)
    vaaniUi.show()
    sys.exit(app.exec_())
